[package]
name = "fast-base62"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
fuzzcheck = "0.12"
proptest = "1"